CREATE TABLE users(
user_id INT AUTO_INCREMENT PRIMARY KEY,
nama VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(20),
phone_number VARCHAR (15),
ROLE VARCHAR(20),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)