CREATE TABLE parking_location(
lokcation_id INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
address TEXT NOT NULL,
latitude DECIMAL(10,8) NOT NULL,
longitude DECIMAL(11,8) NOT NULL,
total_slots INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)